// <auto-generated />
namespace ProjectMayhem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class learningDayFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(learningDayFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202005221446358_learningDayFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
